# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxNetwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Moya
  pod 'Moya/RxSwift', '~> 14.0.0-alpha.1'
  pod 'RxDataSources'
  pod 'RxSwift'
  pod 'RxCocoa'
  

  # Pods for RxNetwork

end
