#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Camera360' do
pod 'SDWebImage'    # 图片下载
pod 'MJExtension'   # 字典转模型
pod 'MJRefresh' # 下拉刷新
pod 'Masonry'   # 自定布局

pod 'AFNetworking'  # 网络请求

end


